### PR TITLE
Youtube Icon Updated

### PR DESCRIPTION
**Pull request by shubham14p3**
-Removed SVG Icon of youtube

### CODE REVIEW

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello! My name is Mario. Good job on your project the appearance is great. 👏 👏  However there are __changes requested by a previous review that you didn't implemented.__

## Changed Required ❗️  

- [x] In the video section, we are currently missing likes and dislike buttons. Let us add them.
We are currently missing the share button and a subscribe button. There is a subscribe text but it is not a button, kindly make it a button. 

- [x] Remember to Validate your HTML before submitting a review https://validator.w3.org/#validate_by_upload

- [x] Please Keep the same pull request for future reviews, remember you should NOT merge into your master branch until the project is approved.

- [ ] Work with git good practices, name your branches with descriptive names, same for your commits

- [x] Give your Pull request a meaningful and descriptive name and description


After making the aforementioned changes please resubmit for review.  

Cheers!! 😄 


## Code review by Mario Enrique Delgado Naranjo

Hi I have already added the custom button & css for it & all have been updated  ,
Kindly check the code without validation.

**Comment by shubham14p3** [comment]
Hi
I have already added the custom button
Have created button with my own tags instead of using predefined Input
button Tag
Kindly let me know why am I being Rejected through Validation, I dont see
my tag issue but in validation I am seeing plenty of error
Kindly let me know what should I do?
Regards

*SHUBHAM RAJ*
*Email :* shubham14p3@gmail.com
*Website :* shubhamraj.dev
*Contact No :* +91 80927 66575

**Comment by MarioDena** [comment]
Hello! Every error on the validation have an explanation, but other issues can cause the validation to give you errors.

If you see a validation error that does not seems to be correct:

I'll check for missing and/or misplaced closing symbols like `"` `()` `<>` `'`. In your case this is the reason for errors.

Also if you have an extra symbol, the same thing will happen. You need to remember to always have pairs for all your `symbols` and `tags`

Cheers!

**Comment by shubham14p3** [comment]
@MarioDena  I have included all the syntax properly , as I know if I miss any of the symbol you are mentioning the HTML tag wont work properly,
I have validated each & every command accordingly.

I have added the custom Like , Dislike button (I have not added it as old school way but adding button tag Instead I have created button class of my self with border 0)
I have added subscription button with button syntax for more details.

Also I have re-validated all the Symbols & Tags , The Tag that are being Popped up 
are generally comments .

Also I tried removing one Entire CSS File , then also I started seeing Frame Ratio error 
If that all valid "630px" not appropriate with error, I belive My code is fine & do let 
me know which part of Code is Giving error & impacting the project,

Kindly don.t validate my project through website, if you do then do let me know what all measure I need to do to solve them on first hand so that I can try , them 

Waiting for your reply

**Comment by uryelah** [comment]
Hello **Shubham Raj**, I'm Sarah, your reviewer for this PR 👩‍🚀 

You did a good job completing some of the required changes from the last review, congrats! 

**Great job at:** 🥇
- making a very nice search bar and button
- adding loader icons
-  paying attention to font size and color
- making a great README.md file
- good job at using normalize.css

**You still need to work on a couple of details before you can move on to the next project though**
-----

### Required changes 🛠 
### 

- [ ] Make a descriptive message for your pull request. Try to follow the bullet point model [used in this link example.](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). You can keep the points from the other code reviews.

- [ ] At `#left-nav-image` please use one image for the logo and one for the hamburger nav icon

- [ ] At `#right-nav-image` each nav icon should be a separated icon. Please don't use screenshots from the page for that. You can try a free icon service like [font-awesome.](https://fontawesome.com/)

- [ ] Add the like, dislike and share icons under the video as [required here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/).

- [ ] At your style.css file, please avoid using ids for styling elements. [Reasons why you should avoid styling with ids.](https://dev.to/clairecodes/reasons-not-to-use-ids-in-css-4ni4)

- [ ] Remember to add this above the recommended videos

Screenshot_2020-03-02 Contributing to Open Source Part I The Easy Way

**[!!ATTENTION!!]** ❗️ 
- [ ] Please fix the validation errors in your HTML markup. https://validator.w3.org/#validate_by_upload
**I noticed you had some issues with this requirement in particular, these are the steps I'd take:**
- Copy the iframe again from a Youtube video to make sure there are no typos.
- Remove the `width` and `height` proprieties from the iframe and set them with CSS instead
- Remove any iframe tag that the validator says is deprecated or unnecessary.

-------

**Please fix the required changes 👷  before asking for a new code review and congrats on starting your journey in Microverse**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
